spring:
  datasource:
    url: jdbc:h2:mem:books_mgt_db;MODE=MySQL
#    url: jdbc:h2:~/h2db/books_mgt_db;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console


logging:
  level:
    org.springframework: debug
    com.github.wangcaide: debug